config/routes.rb
Rails.application.routes.draw do
  get 'order_details/:id/done', to: 'order_details#done', as: 'order_details_done'
  resources :clients
  resources :meals
  resources :ingredients
  resources :orders, only: %i[index new create edit update show]
  get '/orders/:id/close', to: 'orders#close', as: 'close_order'
  resources :kitchen, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes
  has_many :meals, through: :recipes
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :meal_details, dependent: :destroy
  has_many :ingredients, through: :meal_details
  accepts_nested_attributes_for :meal_details, allow_destroy: true,
                                reject_if: ->(attrs) { attrs['ingredient_id'].blank? || attrs['quantity'].blank? }
  has_one_attached :image
end

app/models/meal_detail.rb
class MealDetail < ApplicationRecord
  belongs_to :meal, optional: true
  belongs_to :ingredient, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :client, optional: true
  has_many :order_details, dependent: :destroy
  accepts_nested_attributes_for :order_details, allow_destroy: true,
                                reject_if: ->(attrs) { attrs['meal_id'].blank? || attrs['quantity'].blank? }

  def order_done

  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :meal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  def index
    @clients = Client.all
  end

  # GET /clients/1
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def client_params
      params.require(:client).permit(:name, :last_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  def show; end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit; end

  # POST /ingredients
  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to @ingredient, notice: 'Ingredient was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /ingredients/1
  def update
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient, notice: 'Ingredient was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ingredients/1
  def destroy
    @ingredient.destroy
    redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ingredient_params
    params.require(:ingredient).permit(:name, :unit)
  end
end

app/controllers/kitchen_controller.rb
class KitchenController < ApplicationController

  def index

  end

end

app/controllers/meals_controller.rb
# frozen_string_literal: true

class MealsController < ApplicationController
  before_action :set_meal, only: %i[show edit update destroy]

  # GET /meals
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show; end

  # GET /meals/new
  def new
    @meal = Meal.new
    # 3.times { @meal.recipes.build }
  end

  # GET /meals/1/edit
  def edit; end

  # POST /meals
  def create
    @meal = Meal.new(meal_params)

    if @meal.save
      redirect_to @meal, notice: 'Meal was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /meals/1
  def update
    if @meal.update(meal_params)
      redirect_to @meal, notice: 'Meal was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /meals/1
  def destroy
    @meal.destroy
    redirect_to meals_url, notice: 'Meal was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meal
    @meal = Meal.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def meal_params
    params.require(:meal).permit(:name, :description, :image, :price,
                                 meal_details_attributes: MealDetail.attribute_names.map(&:to_sym).push(:_destroy))
    # recipes_attributes: [:id, :meal_id, :ingredient_id, :quantity, :_destroy]
  end
end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController

  def done
    @order_detail = OrderDetail.find(params[:id])
    @order_detail.done = true
    @order_detail.save
    redirect_to kitchen_index_path
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_detail_params
    params.require(:order_detail).permit(:id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy close]

  # Get /orders
  def index
    puts Order.find_by(closed: false).to_yaml
  end

  # GET /orders/1
  def show; end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # POST /orders
  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to edit_order_path(@order), notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  def close
    @order.closed = true
    @order.save
    redirect_to order_path(@order)
  end

  # GET /orders/1/edit
  def edit; end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def order_params
    params.require(:order).permit(:client_id, :table,
                                 order_details_attributes: OrderDetail.attribute_names.map(&:to_sym).push(:_destroy))
    # recipes_attributes: [:id, :meal_id, :ingredient_id, :quantity, :_destroy]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/kitchen_helper.rb
module KitchenHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class="container">
  <h1>Editing Client</h1>

  <%= render 'form', client: @client %>

  <%= link_to 'Show', @client %> |
  <%= link_to 'Back', clients_path %>
</div>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Clients</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Last name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= client.name %></td>
          <td><%= client.last_name %></td>
          <td><%= link_to 'Show', client %></td>
          <td><%= link_to 'Edit', edit_client_path(client) %></td>
          <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Client', new_client_path %>
</div>

app/views/clients/new.html.erb
<div class="container">
  <h1>New Client</h1>

  <%= render 'form', client: @client %>

  <%= link_to 'Back', clients_path %>
</div>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @client.name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= @client.last_name %>
  </p>

  <%= link_to 'Edit', edit_client_path(@client) %> |
  <%= link_to 'Back', clients_path %>
</div>

app/views/ingredients/_form.html.erb
<%= bootstrap_form_for(@ingredient) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :unit %>
  <%= f.button fa_icon("save", class:"action-icons save-icon", type: :regular), class: "action-button" %>
<% end %>

app/views/ingredients/edit.html.erb
<div class="container">
  <h1>Editing Ingredient</h1>

  <%= render 'form', ingredient: @ingredient %>

  <%= link_to fa_icon("eye", class:"action-icons show-icon"), @ingredient, class: "action-link" %>
  <%= link_to fa_icon("reply", class:"action-icons return-icon"), ingredients_path, class: "action-link" %>
</div>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Ingredients</h1>

  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th>Name</th>
      <th>Unit</th>
      <th style="text-align: center">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.unit %></td>
        <td style="text-align: center">
          <%= link_to fa_icon("eye", class: "action-icons show-icon"), ingredient, class: "action-link" %>
          <%= link_to fa_icon("pencil-alt", class: "action-icons edit-icon"), edit_ingredient_path(ingredient), class: "action-link" %>
          <%= link_to fa_icon("trash", class: "action-icons delete-icon"), ingredient, class: "action-link", method: "delete" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>
  <a title="New Ingredient" class="action-link" href=<%= new_ingredient_path %> ><i class="fa fa-plus action-icons new-icon"></i></a>
</div>

app/views/ingredients/new.html.erb
<div class="container">
  <h1>New Ingredient</h1>

  <%= render 'form', ingredient: @ingredient %>

  <%= link_to fa_icon("reply", class:"action-icons return-icon"), ingredients_path %>
</div>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @ingredient.name %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= @ingredient.unit %>
  </p>

  <%= link_to fa_icon("pencil-alt", class: "action-icons edit-icon"), edit_ingredient_path(@ingredient), class: "action-link", title: "edit" %>
  <%= link_to fa_icon("reply", class:"action-icons return-icon"), ingredients_path, class: "action-link" %>
</div>

app/views/meals/_form.html.erb
<%= form_with(model: meal, local: true) do |f| %>
  <% if meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
        <% meal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Ingredient</th>
      <th>Quantity</th>
      <th>Delete</th>
    </tr>
    </thead>
    <tbody class="ingredients">
      <%= f.fields_for :meal_details do |detail| %>
          <%= render 'meal_detail_fields', f: detail %>
      <% end %>
    </tbody>
  </table>


  <div class="links">
    <%= link_to_add_association 'add ingredient', f, :meal_details, data: {"association-insertion-node" => ".ingredients", "association-insertion-method" => "append"} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meals/_meal_detail_fields.html.erb
<tr class="nested-fields">
  <td><%= f.collection_select(:ingredient_id, Ingredient.all, :id, :name, { prompt: 'Select' }) %></td>
  <td><%= f.text_field :quantity %></td>
  <td><%= link_to_remove_association "Remove Ingredient", f %></td>
</tr>

app/views/meals/edit.html.erb
<div class="container">
  <h1>Editing Meal</h1>

  <%= render 'form', meal: @meal %>

  <%= link_to 'Show', @meal %> |
  <%= link_to 'Back', meals_path %>
</div>

app/views/meals/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Meals</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @meals.each do |meal| %>
        <tr>
          <td><%= meal.name %></td>
          <td><%= meal.description %></td>
          <td><%= meal.price %></td>
          <td><%= link_to 'Show', meal %>
          <%= link_to 'Edit', edit_meal_path(meal) %>
          <%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Meal', new_meal_path %>
</div>

app/views/meals/new.html.erb
<div class="container">
  <h1>New Meal</h1>

  <%= render 'form', meal: @meal %>

  <%= link_to 'Back', meals_path %>
</div>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @meal.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @meal.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @meal.price %>
  </p>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Ingredient</th>
      <th>Quantity</th>
    </tr>
    </thead>
    <tbody>
      <% @meal.meal_details.each do |detail| %>
        <tr>
          <td><%= detail.ingredient.name %></td>
          <td><%= detail.quantity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Edit', edit_meal_path(@meal) %> |
  <%= link_to 'Back', meals_path %>
</div>

app/views/order_details/done.html.erb
<h1>OrderDetails#done</h1>
<p>Find me in app/views/order_details/done.html.erb</p>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meal.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :table %>
    <%= f.number_field :table %>
  </div>

  <div class="field">
    <%= f.label :client %>
    <%= f.collection_select(:client_id, Client.all, :id, :name, { prompt: 'Select' }) %>
  </div>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Meal</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Done</th>
      <th>Delete</th>
    </tr>
    </thead>
    <tbody id="details">
    <%= f.fields_for :order_details do |detail| %>
      <%= render 'order_detail_fields', f: detail %>
    <% end %>
    </tbody>
  </table>


  <div class="links">
    <%= link_to_add_association 'add meal', f, :order_details, data: {"association-insertion-node" => "#details", "association-insertion-method" => "append"} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/orders/_order_detail_fields.html.erb
<tr class="nested-fields">
  <td><%= f.collection_select(:meal_id, Meal.all, :id, :name, { prompt: 'Select' }, { class: 'meal_select' }) %></td>
  <td><%= f.text_field :quantity %></td>
  <td class='price-td'><%= f.text_field :price, class: 'price' %></td>
  <td><%= f.check_box :done %></td>
  <td><%= !f.object.done ? (link_to_remove_association "Remove Meal", f) : "" %></td>
</tr>

app/views/orders/edit.html.erb
<div class="container">
  <h1>Editing Order</h1>

  <%= render 'form', order: @order %>

  <%= link_to 'Close Order', close_order_path(@order) %><br>

  <%= link_to 'Back', orders_path %>
</div>

app/views/orders/index.html.erb
<div class="container">
  <h1>Orders</h1>
  <h2>Pending Orders</h2>

  <table class="table table-striped">
    <thead>
      <tr>
        <td>Order Number</td>
        <td>Table</td>
        <td>Client</td>
        <td>Edit</td>
      </tr>
    </thead>
    <tbody>
    <% Order.where(closed: false).find_each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.table %></td>
        <td><%= if order.client != nil; order.client.name; end %></td>
        <td><%= link_to "edit", edit_order_path(order) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to 'New Order', new_order_path %>

  <h2>All Orders</h2>

  <table class="table table-striped">
    <thead>
    <tr>
      <td>Order Number</td>
      <td>Table</td>
      <td>Client</td>
      <td>Closed?</td>
      <td>Edit</td>
    </tr>
    </thead>
    <tbody>
    <% Order.all.find_each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.table %></td>
        <td><%= if order.client != nil; order.client.name; end %></td>
        <td><%= order.closed %></td>
        <td><%= link_to "edit", edit_order_path(order) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<div class="container">
  <h1>New Order</h1>

  <%= render 'form', order: @order %>

  <%= link_to 'Back', orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <p>
    <strong>Table:</strong>
    <%= @order.table %>
  </p>

  <p>
    <strong>Closed:</strong>
    <%= @order.closed %>
  </p>

  <p>
    <strong>Client:</strong>
    <% if @order.client != nil %>
      <%= @order.client.name %>
    <% end %>
  </p>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Meal</th>
      <th>Quantity</th>
    </tr>
    </thead>
    <tbody>
    <% @order.order_details.each do |detail| %>
      <tr>
        <td><%= detail.meal.name %></td>
        <td><%= detail.quantity %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to 'Edit', edit_order_path(@order) %> |
  <%= link_to 'Back', orders_path %>
</div>