config/routes.rb
Rails.application.routes.draw do
  get 'order_details/:id/done', to: 'order_details#done', as: 'order_details_done'
  resources :clients
  resources :meals
  resources :ingredients
  resources :orders, only: %i[index new create edit update show]
  get '/orders/:id/close', to: 'orders#close', as: 'close_order'
  resources :kitchen, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes
  has_many :meals, through: :recipes
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :meal_details, dependent: :destroy
  has_many :ingredients, through: :meal_details
  accepts_nested_attributes_for :meal_details, allow_destroy: true,
                                reject_if: ->(attrs) { attrs['ingredient_id'].blank? || attrs['quantity'].blank? }
  has_one_attached :image
end

app/models/meal_detail.rb
class MealDetail < ApplicationRecord
  belongs_to :meal, optional: true
  belongs_to :ingredient, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :client, optional: true
  has_many :order_details, dependent: :destroy
  accepts_nested_attributes_for :order_details, allow_destroy: true,
                                reject_if: ->(attrs) { attrs['meal_id'].blank? || attrs['quantity'].blank? }

  def order_done

  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :meal
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  def index
    @clients = Client.all
  end

  # GET /clients/1
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def client_params
      params.require(:client).permit(:name, :last_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

app/controllers/kitchen_controller.rb
class KitchenController < ApplicationController

  def index

  end

end

app/controllers/meals_controller.rb
# frozen_string_literal: true

class MealsController < ApplicationController
  before_action :set_meal, only: %i[show edit update destroy]

  # GET /meals
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show; end

  # GET /meals/new
  def new
    @meal = Meal.new
    # 3.times { @meal.recipes.build }
  end

  # GET /meals/1/edit
  def edit; end

  # POST /meals
  def create
    @meal = Meal.new(meal_params)

    if @meal.save
      redirect_to @meal, notice: 'Meal was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /meals/1
  def update
    if @meal.update(meal_params)
      redirect_to @meal, notice: 'Meal was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /meals/1
  def destroy
    @meal.destroy
    redirect_to meals_url, notice: 'Meal was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meal
    @meal = Meal.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def meal_params
    params.require(:meal).permit(:name, :description, :image, :price,
                                 meal_details_attributes: MealDetail.attribute_names.map(&:to_sym).push(:_destroy))
    # recipes_attributes: [:id, :meal_id, :ingredient_id, :quantity, :_destroy]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy close]

  # Get /orders
  def index
    puts Order.find_by(closed: false).to_yaml
  end

  # GET /orders/1
  def show; end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # POST /orders
  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to edit_order_path(@order), notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  def close
    @order.closed = true
    @order.save
    redirect_to order_path(@order)
  end

  # GET /orders/1/edit
  def edit; end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def order_params
    params.require(:order).permit(:client_id, :table,
                                 order_details_attributes: OrderDetail.attribute_names.map(&:to_sym).push(:_destroy))
    # recipes_attributes: [:id, :meal_id, :ingredient_id, :quantity, :_destroy]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/kitchen_helper.rb
module KitchenHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- Bootstrap 4.4.1 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Bootstrap 4.4.1 JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    <!-- Font Awesome 5.12.0 -->
    <script src="https://kit.fontawesome.com/5ca357b3c0.js" crossorigin="anonymous"></script>

    <title>Demo App (ROR)</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'new_order', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md" id="navbar">
      <%= link_to "App", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Ingredients", ingredients_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Meals", meals_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Clients", clients_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Orders", orders_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Kitchen", kitchen_index_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>

    <footer class="fixed-bottom">
      <div class="container d-flex justify-content-between">
        <p class="inline">Alex Jiñes</p>
        <p>Contact: <a href="mailto:abel.oalex@gmail.com">abel.oalex@gmail.com</a></p>
      </div>
    </footer>
  </body>
</html>